Repository DexterInd/GoPiGo3, pull requests merged in 2018-05, with the labels that each got.

#170 Add Scratch into the Pi menu
  Install/install_scratch.sh
  Software/Scratch/Local_Scratch_Start.desktop
Labels: improvements

#180 feature - change how the installation of the robot goes
  Install/README.md
  Install/install.sh
  Install/update_gopigo3.sh
  README.md
  docs/source/quickstart.rst
Labels: additions, improvements

#183 feature - changing the sources
  Install/update_gopigo3.sh
Labels: improvements

#187 fix - browser bot project
  Projects/RemoteCameraRobot/README.md
  Projects/RemoteCameraRobot/install.sh
  Projects/RemoteCameraRobot/install_startup.sh
  Projects/RemoteCameraRobot/templates/index.html
Labels: problems
