Repository DexterInd/GoPiGo3, pull requests merged in 2018-03, with the labels that each got.

#155 better handling of mutex checking
  Software/Python/easygopigo3.py
Labels: problems

#156 Bug/line follower
  Software/Python/easysensors.py
Labels: problems

#157 Fix/overallmutex
  Software/Python/easysensors.py
Labels: improvements

#159 hotfix - change author name
  docs/source/conf.py
Labels: experience

#162 Fix/trickle down use mutex value
  Software/Python/easygopigo3.py
  Software/Python/easysensors.py
  Software/Python/tests/test_sensor_mutex.py
Labels: improvements

#154 fix - make the intelligent object avoider project work again
  Projects/IntelligentObjectAvoider/README.md
  Projects/IntelligentObjectAvoider/robot.py
Labels: improvements, problems

#165 fix - gopigo3 installer
  Install/install.sh
  Software/Python/I2C_mutex.py
Labels: problems

#166 hotfix - mock I2C_mutex file
  docs/source/conf.py
Labels: problems

#167 new reconfig_bus() method
  Software/Python/easysensors.py
Labels: improvements
