Repository DexterInd/GoPiGo3, pull requests merged in 2018-09, with the labels that each got.

#197 hotfix - remove a duplicate function in the docs
  docs/source/api-basic/structure.rst
Labels: mindless

#199 feature - add kill power method for the servo
  Software/Python/easysensors.py
  docs/source/api-basic/structure.rst
Labels: additions, feedback

#198 hotfix - fix multiple gopigo3 projects & add some READMEs
  Projects/BasicRobotControl/README.md
  Projects/CompassRobot/README.md
  Projects/IntelligentObjectAvoider/README.md
  Projects/IntelligentObjectAvoider/robot.py
  Projects/MouseControl/README.md
  Projects/ObjectAvoidanceRobot/README.md
  Projects/ServoControl/README.md
  Projects/ServoControl/keyboarded_robot.py
Labels: feedback, improvements, problems

#195 hotfix - add gui option & optimize install script
  Install/README.md
  Install/install.sh
  Install/update_gopigo3.sh
Labels: improvements

#200 Line follower improvements
  Software/Python/easysensors.py
Labels: improvements

#202 Fix line follower examples
  Software/Python/Examples/Line_Sensor/README.md
  Software/Python/Examples/Line_Sensor/__init__.py
  Software/Python/Examples/Line_Sensor/basic_example.py
  Software/Python/Examples/Line_Sensor/line_follower-basic_example.py
  Software/Python/Examples/Line_Sensor/line_sensor.py
Labels: problems

#203 fix - the documentation & update the copyright year
  Software/Python/easygopigo3.py
  docs/source/api-basic/structure.rst
  docs/source/conf.py
Labels: problems

#204 sync changes brought in with DexterOS
  Software/Python/Examples/Line_Sensor/README.md
  Software/Python/Examples/Line_Sensor/__init__.py
  Software/Python/Examples/Line_Sensor/basic_example.py
  Software/Python/Examples/Line_Sensor/line_follower-basic_example.py
  Software/Python/Examples/Line_Sensor/line_sensor.py
  Software/Python/easygopigo3.py
  Software/Python/easysensors.py
  docs/source/api-basic/structure.rst
  docs/source/conf.py
Labels: additions, improvements
