Repository DexterInd/GoPiGo3, pull requests merged in 2018-11, with the labels that each got.

#207 hotfix/ fix firmware flashing speed
  Firmware/gopigo3_flash_firmware.sh
Labels: problems

#208 reset speed after exiting from orbit
  Software/Python/easygopigo3.py
Labels: problems

#210 reset speed after exiting from orbit
  Software/Python/easygopigo3.py
Labels: problems

#209 For discussion: set methods to use high speed limit so limit is always from set_speed
  Software/Python/easygopigo3.py
Labels: improvements, pending

#211 feature - tutorial on driving around
  Software/Python/Examples/easy_Motors.py
  docs/source/api-basic/structure.rst
  docs/source/tutorials-basic/button.rst
  docs/source/tutorials-basic/distance_sensor.rst
  docs/source/tutorials-basic/driving.rst
  docs/source/tutorials-basic/index.rst
Labels: additions
