Repository DexterInd/GoPiGo3, pull requests merged in 2019-05, with the labels that each got.

#230 allow distance sensor to be on any port
  Software/Python/easygopigo3.py
Labels: improvements

#231 keeping develop in sync with master changes
  LICENSE.md
  Software/Python/easygopigo3.py
  Software/Python/easysensors.py
  docs/source/tutorials-basic/led.rst
Labels: mindless

#232 feature - config file for gopigo3 constants
  Software/Python/easygopigo3.py
  docs/source/api-basic/structure.rst
Labels: additions, improvements

#233 bring develop to master branch
  Software/Python/easygopigo3.py
  docs/source/api-basic/structure.rst
Labels: additions

#235 add missing exception from the documentation
  Software/Python/easygopigo3.py
Labels: problems

#234 Fix/scratch distancesensor
  Software/Python/easygopigo3.py
  Software/Scratch/GoPiGo3Scratch.py
  Software/Scratch/gopigo3addons.png
  Software/Scratch/gopigo3deprecated.png
  Software/Scratch/gopigo3sensors.png
  Software/Scratch/readme.md
Labels: feedback, improvements

#236 Fix Scratch Distance sensor support
  Software/Python/easygopigo3.py
  Software/Scratch/GoPiGo3Scratch.py
  Software/Scratch/gopigo3addons.png
  Software/Scratch/gopigo3deprecated.png
  Software/Scratch/gopigo3sensors.png
  Software/Scratch/readme.md
Labels: improvements

#240 Support Loudness sensor
  Software/Scratch/GoPiGo3Scratch.py
Labels: feedback, improvements

#241 Loudness sensor Scratch Reference image
  Software/Scratch/gopigo3addons.png
Labels: improvements, mindless
