Repository DexterInd/GoPiGo3, pull requests merged in 2019-03, with the labels that each got.

#215 feature - new line follower
  Projects/PIDLineFollower/README.md
  Projects/PIDLineFollower/menu.PNG
  Projects/PIDLineFollower/pid_tuner.py
  Software/Python/easygopigo3.py
  Software/Python/easysensors.py
  docs/source/api-basic/deprecated.rst
  docs/source/api-basic/easygopigo3.rst
  docs/source/api-basic/index.rst
  docs/source/api-basic/sensors.rst
  docs/source/api-basic/structure.rst
  docs/source/quickstart.rst
  docs/source/tutorials-basic/index.rst
Labels: additions, improvements

#219 take the new line follower code, PID project and documentation into the master branch
  Firmware/gopigo3_flash_firmware.sh
  Projects/PIDLineFollower/README.md
  Projects/PIDLineFollower/menu.PNG
  Projects/PIDLineFollower/pid_tuner.py
  Software/Python/Examples/Line_Sensor/README.md
  Software/Python/Examples/Line_Sensor/basic_example.py
  Software/Python/easygopigo3.py
  Software/Python/easysensors.py
  docs/source/api-basic/deprecated.rst
  docs/source/api-basic/easygopigo3.rst
  docs/source/api-basic/index.rst
  docs/source/api-basic/sensors.rst
  docs/source/api-basic/structure.rst
  docs/source/quickstart.rst
  docs/source/tutorials-basic/index.rst
Labels: additions

#220 Support Line Follower in Scratch
  .gitignore
  Software/Scratch/GoPiGo3Scratch.py
Labels: additions

#224 Feature/antenna led for wifi
  .gitignore
  Install/antenna_wifi.service
  Install/antenna_wifi.sh
  Install/install.sh
Labels: experience, improvements

#225 Update Scratch Example
  Software/Scratch/Examples/GoPiGo3_line_follower.sb
Labels: experience, improvements
